# Generated by Django 4.2.5 on 2023-11-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fecha_evento',
            field=models.DateTimeField(default=None),
        ),
    ]
