# Generated by Django 4.2.5 on 2023-11-05 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_alter_eventos_fecha_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventos',
            new_name='T_Eventos',
        ),
    ]
