# Generated by Django 4.2.5 on 2023-11-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_eventos_t_eventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_eventos',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='t_eventos',
            name='relevancia',
        ),
    ]
