# Generated by Django 4.2.5 on 2023-11-24 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0006_t_eventos_fecha_culminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(blank=True, choices=[('Afgano / Afgana', 'Afgano / Afgana'), ('Alemán / Alemana', '\tAlemán /Alemana'), ('Arabe', 'Arabe'), ('Argentino/Argentina', 'Argentino/Argentina'), ('Australiano/Australiana', 'Australiano/Australiana'), ('Belga', 'Belga'), ('Boliviano/Boliviana', 'Boliviano/Boliviana'), ('Brasileño/Brasileña', 'Brasileño/Brasileña'), ('Camboyano/Camboyana', 'Camboyano/Camboyana'), ('Canadiense', 'Canadiense'), ('Chileno/Chilena', 'Chileno/Chilena'), ('Chino/China', 'Chino/China'), ('Colombiano/Colombiana', 'Colombiano/Colombiana'), ('Coreano/Coreana', 'Coreano/Coreana'), ('Costarricense', 'Costarricense'), ('Cubano/Cubana', 'Cubano/Cubana'), ('Danés/Danesa', 'Danés/Danesa'), ('Ecuatoriano/Ecuatoriana', 'Ecuatoriano/Ecuatoriana'), ('Egipcio/Egipcia', 'Egipcio/Egipcia'), ('Salvadoreño/Salvadoreña', 'Salvadoreño/Salvadoreña'), ('Escocés/Escocesa', 'Escocés/Escocesa'), ('Español/Española', 'Español/Española'), ('Estadounidense', 'Estadounidense'), ('Escocés/Escocesa', 'Escocés/Escocesa'), ('Estonio/Estonia', 'Estonio/Estonia'), ('Etiope', 'Etiope'), ('Filipino/Filipina', 'Filipino/Filipina'), ('Finlandés/Finlandesa', 'Finlandés/Finlandesa'), ('Francés/Francesa', 'Francés/Francesa'), ('Gales/Galesa', 'Gales/Galesa'), ('Griego/Griega', 'Griego/Griega'), ('Guatemalteco/Guatemalteca', 'Guatemalteco/Guatemalteca'), ('Haitiano/Haitiana', 'Haitiano/Haitiana'), ('Holandés/Holandesa', 'Holandés/Holandesa'), ('Hondureño/Hondureña', 'Hondureño/Hondureña'), ('Escocés/Escocesa', 'Escocés/Escocesa'), ('Indonés/Indonesa', 'Indonés/Indonesa'), ('Inglés/Inglesa', 'Inglés/Inglesa'), ('Iraquí', 'Iraquí'), ('Iraní', 'Iraní'), ('Irlandés/Irlandesa', 'Irlandés/Irlandesa'), ('Israelí', 'Israelí'), ('Italiano/Italiana', 'Italiano/Italiana'), ('Japonés/Japonesa', 'Japonés/Japonesa'), ('Jordano/Jordana', 'Jordano/Jordana'), ('Laosiano/Laosiana', 'Laosiano/Laosiana'), ('Letón/Letona', 'Letón/Letona'), ('Letonés/Letonesa', 'Letonés/Letonesa'), ('Malayo/Malaya', 'Malayo/Malaya'), ('Marroquí', 'Marroquí'), ('Mexicano/Mexicana', 'Mexicano/Mexicana'), ('Nicaragüense', 'Nicaragüense'), ('Noruego/Noruega', 'Noruego/Noruega'), ('Neozelandés/Neozelandesa', 'Neozelandés/Neozelandesa'), ('Panameño/Panameña', 'Panameño/Panameña'), ('Paraguayo/Paraguaya', 'Paraguayo/Paraguaya'), ('Peruano/Peruana', 'Peruano/Peruana'), ('Polaco/Polaca', 'Polaco/Polaca'), ('Portugués/Portuguesa', 'Portugués/Portuguesa'), ('Puertorriqueño', 'Puertorriqueño'), ('Dominicano/Dominicana', 'Dominicano/Dominicana'), ('Rumano/Rumana', 'Rumano/Rumana'), ('Ruso/Rusa', 'Ruso/Rusa'), ('Sueco/Sueca', 'Sueco/Sueca'), ('Suizo/Suiza', 'Suizo/Suiza'), ('Tailandés/Tailandesa', 'Tailandés/Tailandesa'), ('Taiwanes/Taiwanesa', 'Taiwanes/Taiwanesa'), ('Turco/Turca', 'Turco/Turca'), ('Ucraniano/Ucraniana', 'Ucraniano/Ucraniana'), ('Uruguayo/Uruguaya', 'Uruguayo/Uruguaya'), ('Venezolano/Venezolana', 'Venezolano/Venezolana'), ('Vietnamita', 'Vietnamita')], max_length=50, null=True)),
                ('pais_residencia', models.CharField(blank=True, choices=[('Afganistán', 'Afganistán'), ('Alemania', 'Alemania'), ('Arabia Saudita', 'Arabia Saudita'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Bélgica', 'Bélgica'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Camboya', 'Camboya'), ('Canadá', 'Canadá'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Corea del Sur', 'Corea del Sur'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Dinamarca', 'Dinamarca'), ('Ecuador', 'Ecuador'), ('Egipto', 'Egipto'), ('El Salvador', 'El Salvador'), ('Escocia', 'Escocia'), ('España', 'España'), ('Estados Unidos', 'Estados Unidos'), ('Estonia', 'Estonia'), ('Etiopia', 'Etiopia'), ('Filipinas', 'Filipinas'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Gales', 'Gales'), ('Grecia', 'Grecia'), ('Guatemala', 'Guatemala'), ('Haití', 'Haití'), ('Holanda', 'Holanda'), ('Honduras', 'Honduras'), ('Gales', 'Gales'), ('Indonesia', 'Indonesia'), ('Inglaterra', 'Inglaterra'), ('Irak', 'Irak'), ('Irán', 'Irán'), ('Irlanda', 'Irlanda'), ('Israel', 'Israel'), ('Italia', 'Italia'), ('Japón', 'Japón'), ('Jordania', 'Jordania'), ('Laos', 'Laos'), ('Letonia', 'Letonia'), ('Lituania', 'Lituania'), ('Malasia', 'Malasia'), ('Marruecos', 'Marruecos'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Noruega', 'Noruega'), ('Nueva Zelandia', 'Nueva Zelandia'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Republica Dominicana', 'Republica Dominicana'), ('Rumania', 'Rumania'), ('Rusia', 'Rusia'), ('Suecia', 'Suecia'), ('Suiza', 'Suiza'), ('Tailandia', 'Tailandia'), ('Taiwán', 'Taiwán'), ('Turquía', 'Turquía'), ('Ucrania', 'Ucrania'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam')], max_length=50, null=True)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_documento', models.CharField(blank=True, choices=[('Cedula de Identidad', 'Cedula de Identidad'), ('Pasaporte', 'Pasaporte'), ('RIF', 'RIF')], max_length=50, null=True)),
                ('n_documento', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.t_eventos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
