# Generated by Django 4.2.5 on 2023-11-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_t_participantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T_Participantes',
        ),
    ]
