# Generated by Django 4.2.5 on 2023-11-12 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0008_delete_t_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('n_documento', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.t_eventos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
