# Generated by Django 4.2.5 on 2023-11-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_t_participantes_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_participantes',
            old_name='documento',
            new_name='tipo_documento',
        ),
    ]
